# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_personnel_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='phdtopic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
