# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_personnel_extern_advisors'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='fonction1',
            field=models.CharField(blank=True, choices=[('Maître de conférences (CNAM)', 'Maître de conférences (CNAM)'), ('Ingénieur de recherche (EP/X)', 'Ingénieur de recherche (EP/X)'), ('Directeur de recherche (CNRS)', 'Directeur de recherche (CNRS)'), ('Professeur chargé de cours (EP/X)', 'Professeur chargé de cours (EP/X)'), ('Chargé de recherche (CNRS)', 'Chargé de recherche (CNRS)'), ('Directeur de recherche (CNRS) - Directeur du LadHyX', 'Directeur de recherche (CNRS) - Directeur du LadHyX'), ('Professeur (EP/X) - Président du Département de Mécanique', 'Professeur (EP/X) - Président du Département de Mécanique'), ('Maître de conférences (EP/X)', 'Maître de conférences (EP/X)'), ('Ingénieur de recherche (CNRS)', 'Ingénieur de recherche (CNRS)'), ('Directeur de recherche émérite (CNRS)', 'Directeur de recherche émérite (CNRS)'), ('Chargé de recherche (CNRS)', 'Chargé de recherche (CNRS)'), ('Maître de conférences (EP/X) - Directeur-adjoint du LadHyX', 'Maître de conférences (EP/X) - Directeur-adjoint du LadHyX'), ('Enseignante-chercheuse (ENSTA)', 'Enseignante-chercheuse (ENSTA)'), ('Chercheur associé (CNRS)', 'Chercheur associé (CNRS)'), ('Professeur associé (EP/X)', 'Professeur associé (EP/X)'), ('Doctorant', 'Doctorant'), ('Chercheur postdoctoral', 'Chercheur postdoctoral'), ("Ingénieur d'études", "Ingénieur d'études"), ('Technicien mécanicien', 'Technicien mécanicien'), ('Secrétariat de direction, Missions', 'Secrétariat de direction, Missions'), ('Administratrice, Ressource humaines', 'Administratrice, Ressource humaines'), ('Gestionnaire, secrétaire', 'Gestionnaire, secrétaire'), ('Ingénieur systèmes', 'Ingénieur systèmes')], max_length=100),
        ),
        migrations.AddField(
            model_name='personnel',
            name='fonction2',
            field=models.CharField(blank=True, choices=[('Maître de conférences (CNAM)', 'Maître de conférences (CNAM)'), ('Ingénieur de recherche (EP/X)', 'Ingénieur de recherche (EP/X)'), ('Directeur de recherche (CNRS)', 'Directeur de recherche (CNRS)'), ('Professeur chargé de cours (EP/X)', 'Professeur chargé de cours (EP/X)'), ('Chargé de recherche (CNRS)', 'Chargé de recherche (CNRS)'), ('Directeur de recherche (CNRS) - Directeur du LadHyX', 'Directeur de recherche (CNRS) - Directeur du LadHyX'), ('Professeur (EP/X) - Président du Département de Mécanique', 'Professeur (EP/X) - Président du Département de Mécanique'), ('Maître de conférences (EP/X)', 'Maître de conférences (EP/X)'), ('Ingénieur de recherche (CNRS)', 'Ingénieur de recherche (CNRS)'), ('Directeur de recherche émérite (CNRS)', 'Directeur de recherche émérite (CNRS)'), ('Chargé de recherche (CNRS)', 'Chargé de recherche (CNRS)'), ('Maître de conférences (EP/X) - Directeur-adjoint du LadHyX', 'Maître de conférences (EP/X) - Directeur-adjoint du LadHyX'), ('Enseignante-chercheuse (ENSTA)', 'Enseignante-chercheuse (ENSTA)'), ('Chercheur associé (CNRS)', 'Chercheur associé (CNRS)'), ('Professeur associé (EP/X)', 'Professeur associé (EP/X)'), ('Doctorant', 'Doctorant'), ('Chercheur postdoctoral', 'Chercheur postdoctoral'), ("Ingénieur d'études", "Ingénieur d'études"), ('Technicien mécanicien', 'Technicien mécanicien'), ('Secrétariat de direction, Missions', 'Secrétariat de direction, Missions'), ('Administratrice, Ressource humaines', 'Administratrice, Ressource humaines'), ('Gestionnaire, secrétaire', 'Gestionnaire, secrétaire'), ('Ingénieur systèmes', 'Ingénieur systèmes')], max_length=100),
        ),
    ]
