# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_auto_20171017_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='fonction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='fonction1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='fonction2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
