# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-05 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_auto_20171023_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='lieu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='bureau',
        ),
        migrations.AddField(
            model_name='personnel',
            name='bureau',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
