# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-05 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_auto_20181005_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='bureau',
        ),
        migrations.AddField(
            model_name='personnel',
            name='bureau',
            field=models.ManyToManyField(blank=True, to='personnel.Bureau'),
        ),
    ]
