# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('intitule_id', models.AutoField(primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Séminaires', 'Séminaires'), ('colloques', 'Colloques'), ('soutenances', 'Soutenances'), ('Evenements', 'Evenements')], max_length=100)),
                ('personne', models.CharField(max_length=255)),
                ('institut', models.CharField(blank=True, max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(blank=True, choices=[('LadHyX Library', 'LadHyX Library'), ('Lecture Hall, Turing building', 'Lecture Hall, Turing building')], max_length=255)),
                ('heure', models.TimeField(blank=True, null=True)),
                ('resume', models.TextField(blank=True)),
                ('abstract', models.FileField(blank=True, default='', upload_to='evenement')),
                ('lien', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Evènement',
                'verbose_name_plural': 'Evènement',
            },
        ),
    ]
