# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Evenement',
            name='domaine',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='Evenement',
            name='type',
            field=models.CharField(choices=[('Séminaires', 'Séminaires'), ('Soutenances', 'Soutenances')], max_length=100),
        ),
    ]
