# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0002_auto_20171023_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Evenement',
            name='type',
            field=models.CharField(choices=[('Séminaires', 'Séminaires')], max_length=100),
        ),
    ]
