# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-24 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0003_auto_20171025_1019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actualites',
            new_name='Evenement',
        ),
    ]
